# see: https://platform.openai.com/api-keys

# chat-01-test02-key
@api_key = {{$dotenv OPENAI_KEY}}

@model = gpt-4o-mini

@api_url = https://api.openai.com/v1/chat/completions

###
POST {{api_url}}
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
  "model": "{{model}}",
  "messages": [
    {
      "role": "system",
      "content": "Responde con un cuestionario para evaluar conocimientos a modo de juego de preguntas y respuestas. Cada campo de texto puede tener como máxima 30 palabras, salvo las descripciones que pueden tener hasta 300. Se creativo al elegir el título del cuestionario. usa la descripcion para brindar contexto y contenido didáctico acerca del cuestionario y cada pregunta, sin revelar la respuesta. Responde únicamente con un JSON con esta estructura de TypeScript:\n{\n  id: `enc_${string}` // identificador de cuestionario\n  titulo: string // título del cuestionario\n  descripcion: string\n  preguntas: [\n    id: `preg_${string} // identificador de pregunta\n    {\n      titulo: string // texto de la pregunta\n      descripcion: string // texto de la pregunta\n      tipo: 'unica'\n      opciones: string[]\n      respuesta: string\n    }\n  ]\n}"
    },
    {
      "role": "user",
      "content": "genera un cuestionario sobre 'Literatura argentina', con '5' preguntas, dificultad 'Muy difícil'"
    }
  ],
  "stream": false,
  "temperature": 1,
  "max_tokens": 1192,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "response_format": {
    "type": "text"
  }
}

###
POST {{api_url}}
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
  "model": "{{model}}",
  "messages": [
    {
      "role": "system",
      "content": "retorná unicamente un JSON que responda a esta definición de TypeScript: string[]"
    },
    {
      "role": "user",
      "content": "Las 5 mejores ciudades de Argentina para visitar"
    }
  ],
  "stream": false,
  "temperature": 1,
  "max_tokens": 1192,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "response_format": {
    "type": "text"
  }
}

###
POST http://localhost:3000/api/generate
Content-Type: application/json

{
  "system": "retorná unicamente un JSON que responda a esta definición de TypeScript: string[]",
  "user": "Las 5 mejores ciudades de Argentina para visitar"
}

###
POST http://localhost:3000/api/generate
Content-Type: application/json

{
  "system": "retorná unicamente un JSON que responda a esta definición de TypeScript: Array<{ nombre: string, poblacion: number, superficie: number, hab_x_km2: number }>",
  "user": "Las 5 mejores ciudades de Argentina para visitar"
}

###
POST http://localhost:3000/api/generate
Content-Type: application/json

{
  "user": "Las 3 mejores ciudades del mundo para visitar, solo la lista"
}

###
POST http://localhost:3000/api/generate
Content-Type: application/json

"Las 3 mejores ciudades del mundo para visitar, solo la lista"

###
POST http://localhost:3000/api/generate
Content-Type: application/json

{
	"system": "Responde con un cuestionario para evaluar conocimientos a modo de juego de preguntas y respuestas. Cada campo de texto puede tener como máxima 30 palabras, salvo las descripciones que pueden tener hasta 300. Se creativo al elegir el título del cuestionario. usa la descripcion para brindar contexto y contenido didáctico acerca del cuestionario y cada pregunta, sin revelar la respuesta. Responde únicamente con un JSON con esta estructura de TypeScript:\n{\n  id: `enc_${string}` // identificador de cuestionario\n  titulo: string // título del cuestionario\n  descripcion: string\n  preguntas: [\n    id: `preg_${string} // identificador de pregunta\n    {\n      titulo: string // texto de la pregunta\n      descripcion: string // texto de la pregunta\n      tipo: 'unica'\n      opciones: string[]\n      respuesta: string\n    }\n  ]\n}",
	"user": "genera un cuestionario sobre 'Literatura argentina', con '5' preguntas, dificultad 'Muy difícil'"
}