name: Unit and Integration tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  OPENAI_KEY: sk-proj-...placeholder
  OPENAI_URL: https://api.openai.com/v1/chat/completions
  OLLAMA_URL: http://localhost:11434/api/generate

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # check package.json packageManager entry: "packageManager": "^pnpm@9.6.0",
        # with:
        # version: '9.6.0' # or any other version you need

      - name: Install dependencies
        run: pnpm install

      - name: Unit tests
        run: pnpm test:unit --run

      - name: Install playwright
        run: pnpm exec playwright install

      - name: Integration tests
        run: pnpm test:integration
